config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  resources :users
  resources :marketings
  resources :tests
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:subdomain, :username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:subdomain, :username, :email, :password, :remember_me) }
  end
end

app/models/marketing.rb
class Marketing < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
has_many :marketings, dependent: :destroy
          # 認証で使うキーを指定
  devise :database_authenticatable, :validatable,
  authentication_keys: [:username]

  attachment :profile_image

# 登録時に email を不要にする
def email_required?
  false
end
def email_changed?
  false
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :detect_device
  private
    def detect_device
      case request.user_agent
        when /iPad/
            request.variant = :mobile
        when /iPod/
            request.variant = :mobile
        when /iPhone/
            request.variant = :mobile
        when /Android/
            request.variant = :mobile
      end
    end
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/marketings_controller.rb
class MarketingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @marketings= Marketing.all
  end

  def new 
    @marketing = Marketing.new
  end

  def create 
    @marketing = Marketing.new(marketing_params)
    @marketing.user_id = current_user.id
    
    if @marketing.save
      redirect_to marketing_path(@marketing),notice: '素晴らしいアイデアです！'
     
      else
        render :new
      end
  end

  def show
    @marketing = Marketing.find(params[:id])
  end

  def edit
    @marketing = Marketing.find(params[:id])
  end

  def update
    @marketing = Marketing.find(params[:id])
    if @marketing.update(marketing_params)
    redirect_to marketing_path(@marketing),notice: '更新しました'
    else
      render :edit
  end
end

def destroy
  marketing = Marketing.find(params[:id])
  marketing.destroy
  redirect_to user_path(marketing.user), notice: "消しやした"
end


  private
def marketing_params
  params.require(:marketing).permit(:company,:consumer,:costomer,:competitor,:community,:object,:st,:pp1,:pp2,:pp3,:kenzai,:senzai,:insight,:what,:how1,:how2,:how3,:explanation)
end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit 
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:profile,:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marketings_helper.rb
module MarketingsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: cursive;">marketing team<br>yaiba</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>マーケティングチーム刃</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">Marketing yaiba</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
          
          </div>
          <div class="navbar-item">
           
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "刃メンバー", users_path, class: " button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "戦略一覧", marketings_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "刃メンバー", users_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </p>
               
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/marketings/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
       戦略編集
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
      <h2>戦況分析</h2>
        <%= form_for @marketing do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="field">
            <%= f.label :company, "自社の理解", class: "label" %>
            <%= f.text_area :company, size: "70x5",class: "large" %>
          </div>
          <div class="field">
            <%= f.label :consumer, "消費者の理解", class: "label" %>
            <%= f.text_area :consumer, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :costomer, "中間顧客の理解", class: "label" %>
            <%= f.text_area :costomer, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :competitor, "競合する他社の理解", class: "label" %>
            <%= f.text_area :competitor, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :community, "ビジネスを取り巻く環境の理解", class: "label" %>
            <%= f.text_area :community, class: "input" %>
          </div>
          <br>
          <br>
          <h2>戦略</h2>
          <div class="field">
            <%= f.label :object, "目的", class: "label" %>
            <%= f.text_field :object, class: "input" %>
          </div>
          <h2>WHO</h2>
          <div class="field">
            <%= f.label :st, "ST", class: "label" %>
            <%= f.text_field :st, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :pp1, "PP1", class: "label" %>
            <%= f.text_field :pp1, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :pp2, "PP2", class: "label" %>
            <%= f.text_field :pp2, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :pp3, "pp3", class: "label" %>
            <%= f.text_field :pp3, class: "input" %>
          </div>
          <div class="field">
          <%= f.label :kenzai, "顕在ニーズ", class: "label" %>
          <%= f.text_area :kenzai, class: "input" %>
        </div>
        <div class="field">
          <%= f.label :senzai, "潜在ニーズ", class: "label" %>
          <%= f.text_area :senzai, class: "input" %>
        </div>
        <div class="field">
          <%= f.label :insight, "インサイト", class: "label" %>
          <%= f.text_area :insight, class: "input" %>
        </div>
        <h2>WHAT</h2>
        <div class="field">
        <%= f.label :what, "真の価値", class: "label" %>
        <%= f.text_field :what, class: "input" %>
      </div>
      <h2>HOW</h2>
      <div class="field">
      <%= f.label :how1, "プラン１", class: "label" %>
      <%= f.text_area :how1, class: "input" %>
    </div>
    <div class="field">
      <%= f.label :how2, "プラン２", class: "label" %>
      <%= f.text_area :how2, class: "input" %>
    </div>
    <div class="field">
      <%= f.label :how3, "プラン３", class: "label" %>
      <%= f.text_area :how3, class: "input" %>
    </div>

    <div class="field">
      <%= f.label :explanation, "想いや懸念点等", class: "label" %>
      <%= f.text_area :explanation, class: "input" %>
    </div>
          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/marketings/index.html.erb
<section class="hero is-info" %>
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @marketings.each do |marketing| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              
                <%= link_to marketing_path(marketing) do %>
                  <%= marketing.object %>
                <% end %>
              
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag marketing.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to marketing.user.username, user_path(marketing.user) %></div>
                </div>
              </div>
              
              <div class="content">
                <time><%= marketing.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/marketings/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
       戦略立案
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
      <h2>戦況分析</h2>
        <%= form_for @marketing do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="field">
            <%= f.label :company, "自社の理解", class: "label" %>
            <%= f.text_area :company, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :consumer, "消費者の理解", class: "label" %>
            <%= f.text_area :consumer, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :costomer, "中間顧客の理解", class: "label" %>
            <%= f.text_area :costomer, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :competitor, "競合する他社の理解", class: "label" %>
            <%= f.text_area :competitor, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :community, "ビジネスを取り巻く環境の理解", class: "label" %>
            <%= f.text_area :community, class: "input" %>
          </div>
          <br>
          <br>
          <h2>戦略</h2>
          <div class="field">
            <%= f.label :object, "目的", class: "label" %>
            <%= f.text_field :object, class: "input" %>
          </div>
          <h2>WHO</h2>
          <div class="field">
            <%= f.label :st, "ST", class: "label" %>
            <%= f.text_field :st, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :pp1, "PP1", class: "label" %>
            <%= f.text_field :pp1, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :pp2, "PP2", class: "label" %>
            <%= f.text_field :pp2, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :pp3, "pp3", class: "label" %>
            <%= f.text_field :pp3, class: "input" %>
          </div>
          <div class="field">
          <%= f.label :kenzai, "顕在ニーズ", class: "label" %>
          <%= f.text_area :kenzai, class: "input" %>
        </div>
        <div class="field">
          <%= f.label :senzai, "潜在ニーズ", class: "label" %>
          <%= f.text_area :senzai, class: "input" %>
        </div>
        <div class="field">
          <%= f.label :insight, "インサイト", class: "label" %>
          <%= f.text_area :insight, class: "input" %>
        </div>
        <h2>WHAT</h2>
        <div class="field">
        <%= f.label :what, "真の価値", class: "label" %>
        <%= f.text_field :what, class: "input" %>
      </div>
      <h2>HOW</h2>
      <div class="field">
      <%= f.label :how1, "プラン１", class: "label" %>
      <%= f.text_area :how1, class: "input" %>
    </div>
    <div class="field">
      <%= f.label :how2, "プラン２", class: "label" %>
      <%= f.text_area :how2, class: "input" %>
    </div>
    <div class="field">
      <%= f.label :how3, "プラン３", class: "label" %>
      <%= f.text_area :how3, class: "input" %>
    </div>

    <div class="field">
      <%= f.label :explanation, "想いや懸念点等", class: "label" %>
      <%= f.text_area :explanation, class: "input" %>
    </div>
          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/marketings/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        戦略詳細
      </h1>
    </div>
  </div>
</section>

<section class="pre-about">
<div class="edit">
<% if @marketing.user.id == current_user.id %>
<%= link_to "編集画面へ", edit_marketing_path(@marketing), class: "button is-success" %>
<% end %>
</div>
<h2><%= link_to @marketing.user.username,user_path(@marketing.user) %>さんの戦略</h2><h3>戦況分析</h3>
<div class="about-text">
<h4>自社の理解</h4>
<p><%= @marketing.company %></p>
</div>
<div class="about-border"></div>
<div class="about-text">
<h4>消費者の理解</h4>
<p><%=@marketing.consumer %></p>
</div>
<div class="about-border"></div>
<div class="about-text">
<h4>中間顧客の理解</h4>
<p><%= @marketing.costomer %></p>
</div>
<div class="about-border"></div>
<div class="about-text">
<h4>競合する他社の理解</h4>
<p><%=@marketing.competitor %></p>
</div>
<div class="about-border"></div>
<div class="about-text">
<h4>ビジネスを取り巻く環境の理解</h4>
<p><%=@marketing.community %></p>
</div>
<div class="about-border"></div>
</section>

<section class="pickup">
<div class="tile is-ancestor">
<div class="column is-three-fifths is-offset-one-fifth">
<div class="tile is-12 is-vertical is-parent">
<div class="tile is-child box">
<p class="title">目的</p>
<p><%= @marketing.object %></p>
</div>
<div class="tile is-child box">
        <p class="title">WHO</p>
        <p>ST:   <%= @marketing.st %><br>
        PP1:   <%= @marketing.pp1 %><br>
        PP2:   <%= @marketing.pp2 %><br>
        PP3:   <%= @marketing.pp3 %></p>
 </div>
</div>
<div class="columns">
  <div class="column is-half">
  <div class="tile is-parent ">
  <div class="tile is-child box">
   <p class="title" style="font-size:25px;">顕在ニーズ</p>
        <p><%= @marketing.kenzai %></p>
    </div>
  </div>
  </div>
  <div class="column">
  <div class="tile is-parent ">
  <div class="tile is-child box">
        <p class="title" style="font-size:25px;">潜在ニーズ</p>
        <p><%= @marketing.senzai %></p>
   </div>
  </div>
 </div>
</div>
<div class="tile is-ancestor">
<div class="tile is-12 is-vertical is-parent">
<div class="tile is-child box">
<p class="title" style="font-size:25px;">インサイト</p>
<p><%= @marketing.insight %></p>
</div>
<div class="tile is-child box">
        <p class="title" style="font-size:25px;">WHAT</p>
        <p><%= @marketing.what %></p>
 </div>
<div class="tile is-child box">
        <p class="title" style="font-size:25px;">HOW（プラン１）</p>
        <p><%= @marketing.how1 %></p>
 </div>
 <div class="tile is-child box">
        <p class="title" style="font-size:25px;">HOW（プラン２）</p>
        <p><%= @marketing.how2 %></p>
 </div>
 <div class="tile is-child box">
        <p class="title" style="font-size:25px;">HOW（プラン３）</p>
        <p><%= @marketing.how3 %></p>
 </div>
 <div class="tile is-child box">
        <p class="title" style="font-size:25px;">想いや懸念点など</p>
        <p><%= @marketing.explanation %></p>
 </div>
</div>

</div>
</div>
</div>
</div>
</section>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
   <div id="error_messages" class="alert alert-danger">
     <ul class="mb-0">
       <% object.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>


          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
       刃メンバー
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" ,size: '320x240' %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">
                投稿数：<%= user.marketings.count %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.marketings.each do |m| %>
        <div class="column is-4">
          <div class="card">
           <%= m.object %>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to marketing_path(m), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この投稿を見る
                  <% end %>
                  
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_marketing_path(m), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この投稿を編集する
                    <% end %>
                    <%= link_to marketing_path(m), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この投稿を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= m.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>